ROOT = ../..
NAME = getting_started

GENERATED_FILES = \
  getting_started_csml.cs getting_started_csml.ml getting_started_cs.ml

MLCODE = \
  getting_started_cs.ml getting_started.ml getting_started_csml.ml

CSCODE = \
  getting_started.cs getting_started_csml.cs

include $(ROOT)/Makefile.examples
