ROOT = ../..
NAME = opaque_binding

GENERATED_FILES= \
  opaque_binding_csml.cs opaque_binding_csml.ml opaque_binding_cs.ml

MLCODE = \
  opaque_binding_cs.ml opaque_binding.ml opaque_binding_csml.ml

CSCODE = \
  opaque_binding.cs opaque_binding_csml.cs

include $(ROOT)/Makefile.examples
