ROOT = ../..
NAME = structured_mapping

GENERATED_FILES=\
  structured_mapping_csml.cs structured_mapping_csml.ml

MLCODE = \
  structured_mapping.ml structured_mapping_csml.ml

CSCODE = \
  structured_mapping.cs structured_mapping_csml.cs

include $(ROOT)/Makefile.examples
